name: Simulation

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Webots
      run: |
        wget https://github.com/cyberbotics/webots/releases/download/R2020a-rev1/webots-R2020a-rev1-x86-64.tar.bz2
        tar xjf webots-R2020a-rev1-x86-64.tar.bz2
    - name: Install Webots Dependencies
      run: sudo apt -y install xserver-xorg-core libpulse0 libglu1-mesa g++ cmake libusb-dev swig python2.7-dev libglu1-mesa-dev libglib2.0-dev libfreeimage-dev libfreetype6-dev libxml2-dev libzzip-0-13 libssl1.0-dev libboost-dev libavcodec-extra libgd-dev libssh-gcrypt-dev libzip-dev python-pip libreadline-dev libassimp-dev ffmpeg npm python3.6-dev python3.7-dev openjdk-11-jdk curl fakeroot pbzip2 libxkbcommon-x11-dev
    - name: Run Test
      run: |
        export WEBOTS_HOME=$PWD/webots
        export LIBGL_ALWAYS_SOFTWARE=true
        xvfb-run --auto-servernum $WEBOTS_HOME/webots --version
        xvfb-run --auto-servernum $WEBOTS_HOME/webots --sysinfo
        xvfb-run --auto-servernum python $GITHUB_WORKSPACE/tests/test_suite.py
        xvfb-run --auto-servernum $WEBOTS_HOME/webots  $WEBOTS_HOME/projects/samples/devices/worlds/gyro.wbt --stdout --stderr --batch --minimize
